# Generated by Django 2.2.7 on 2019-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191117_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='degisecek'),
        ),
    ]
