# Generated by Django 2.2.7 on 2019-12-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='upload/avatars/default.jpg', upload_to='upload/avatars'),
        ),
    ]
